### ISSUE TITLE
Update CWHost for 2015-05-05-raspbian-wheezy

### ISSUE THREAD

**Issue by SouthPaw-42** [area515/Creation-Workshop-Host#51] opened 2015-07-16 03:23 UTC
Update CWHost for 2015-05-05-raspbian-wheezy and update instructions please

**Comment by WesGilster** [comment] 2015-07-17 03:08
In what way does CWH need to be updated for the latest version? Also, how do the instructions need to be changed?

**Comment by SouthPaw-42** [comment] 2015-07-17 17:21
When I tried to install CWHost I received errors. I will try install again and document the errors.
 I also can't find raspi-config-cwhost.sh anywhere after install.

**Comment by WesGilster** [comment] 2015-07-19 20:13
I don't believe we have ever installed raspi-config-cwhost.sh with the application. It's pretty experimental right now. Thanks for the help testing!

**Comment by sbryan** [comment] 2015-07-20 14:59
@SouthPaw-42, I've tested and debugged the raspi-config-cwhost.sh, and as @WesGilster indicates, it really is experimental.  I've written down a bunch of changes, and started making the changes necessary, but haven't had time yet to finish and submit a pull request.  I'll try to do that this week maybe...

For now though, I wouldn't even run it... it actually does more harm than good, and re-running it on a system it was already run on can make things worse.

**Comment by WesGilster** [comment] 2015-08-10 18:40
Marking this a duplicate of #47

**Closed by WesGilster** 2015-08-10 18:40 UTC
